"""
Test script for Content Layer implementation
Tests that content is created and can be managed through the API
"""
import requests
import json
from uuid import UUID
from datetime import datetime

# Base URL
BASE_URL = "http://localhost:8000"

# Test data
WORKSPACE_ID = None
WORKFLOW_ID = None
JOB_ID = None
CONTENT_ID = None

def print_section(title):
    print(f"\n{'='*60}")
    print(f"  {title}")
    print('='*60)

def test_1_create_workspace():
    """Step 1: Create a test workspace"""
    global WORKSPACE_ID
    
    print_section("TEST 1: Create Workspace")
    
    # Generate a test user_id (in production this would come from auth)
    import uuid
    user_id = str(uuid.uuid4())
    
    response = requests.post(
        f"{BASE_URL}/api/workspaces",
        json={
            "owner_user_id": user_id,
            "name": "Content Test Workspace"
        }
    )
    
    print(f"Status: {response.status_code}")
    data = response.json()
    print(f"Response: {json.dumps(data, indent=2, default=str)}")
    
    if response.status_code == 200:
        WORKSPACE_ID = data["id"]
        print(f"✅ Workspace created: {WORKSPACE_ID}")
        return True
    else:
        print(f"❌ Failed to create workspace")
        return False

def test_2_create_workflow_with_caption_generator():
    """Step 2: Create a workflow that generates captions"""
    global WORKFLOW_ID
    
    print_section("TEST 2: Create Workflow with Caption Generator")
    
    if not WORKSPACE_ID:
        print("❌ No workspace ID available")
        return False
    
    response = requests.post(
        f"{BASE_URL}/api/workflows",
        json={
            "workspace_id": WORKSPACE_ID,
            "name": "LinkedIn Caption Workflow",
            "description": "Generate captions for LinkedIn posts",
            "target_platform": "linkedin",
            "steps": [
                {
                    "order": 1,
                    "name": "Generate Caption",
                    "tool_name": "caption_generator",
                    "config": {
                        "topic": "productivity tips for remote work",
                        "platform": "linkedin",
                        "tone": "professional"
                    }
                }
            ]
        }
    )
    
    print(f"Status: {response.status_code}")
    data = response.json()
    print(f"Response: {json.dumps(data, indent=2, default=str)}")
    
    if response.status_code == 200:
        WORKFLOW_ID = data["id"]
        print(f"✅ Workflow created: {WORKFLOW_ID}")
        return True
    else:
        print(f"❌ Failed to create workflow")
        return False

def test_3_run_workflow():
    """Step 3: Run the workflow to generate content"""
    global JOB_ID
    
    print_section("TEST 3: Run Workflow")
    
    if not WORKFLOW_ID:
        print("❌ No workflow ID available")
        return False
    
    response = requests.post(f"{BASE_URL}/api/workflows/{WORKFLOW_ID}/run")
    
    print(f"Status: {response.status_code}")
    data = response.json()
    print(f"Response: {json.dumps(data, indent=2, default=str)}")
    
    if response.status_code == 200:
        JOB_ID = data["job_id"]
        print(f"✅ Job started: {JOB_ID}")
        print("⏳ Waiting for job to complete...")
        
        # Poll job status
        import time
        max_attempts = 30
        for attempt in range(max_attempts):
            time.sleep(2)
            status_response = requests.get(f"{BASE_URL}/api/jobs/{JOB_ID}")
            if status_response.status_code == 200:
                job_data = status_response.json()
                status = job_data.get("status")
                progress = job_data.get("progress", 0)
                print(f"  Attempt {attempt + 1}: Status={status}, Progress={progress}%")
                
                if status == "completed":
                    print("✅ Job completed successfully")
                    return True
                elif status == "failed":
                    print(f"❌ Job failed: {job_data.get('error')}")
                    return False
        
        print("⏱️ Job still running after 60 seconds")
        return False
    else:
        print(f"❌ Failed to start workflow")
        return False

def test_4_list_content():
    """Step 4: List content generated by the job"""
    global CONTENT_ID
    
    print_section("TEST 4: List Content")
    
    if not WORKSPACE_ID:
        print("❌ No workspace ID available")
        return False
    
    response = requests.get(
        f"{BASE_URL}/api/content/",
        params={"workspace_id": WORKSPACE_ID}
    )
    
    print(f"Status: {response.status_code}")
    data = response.json()
    print(f"Response: {json.dumps(data, indent=2, default=str)}")
    
    if response.status_code == 200:
        if len(data) > 0:
            CONTENT_ID = data[0]["id"]
            print(f"✅ Found {len(data)} content item(s)")
            print(f"   Content ID: {CONTENT_ID}")
            print(f"   Type: {data[0]['content_type']}")
            print(f"   Status: {data[0]['status']}")
            return True
        else:
            print("❌ No content found")
            return False
    else:
        print(f"❌ Failed to list content")
        return False

def test_5_get_content_details():
    """Step 5: Get detailed content"""
    print_section("TEST 5: Get Content Details")
    
    if not CONTENT_ID:
        print("❌ No content ID available")
        return False
    
    response = requests.get(f"{BASE_URL}/api/content/{CONTENT_ID}")
    
    print(f"Status: {response.status_code}")
    data = response.json()
    print(f"Response: {json.dumps(data, indent=2, default=str)}")
    
    if response.status_code == 200:
        print(f"✅ Content retrieved successfully")
        print(f"   Generated Caption: {data['data'].get('caption', 'N/A')[:100]}...")
        return True
    else:
        print(f"❌ Failed to get content")
        return False

def test_6_approve_content():
    """Step 6: Approve the content"""
    print_section("TEST 6: Approve Content")
    
    if not CONTENT_ID:
        print("❌ No content ID available")
        return False
    
    response = requests.post(f"{BASE_URL}/api/content/{CONTENT_ID}/approve")
    
    print(f"Status: {response.status_code}")
    data = response.json()
    print(f"Response: {json.dumps(data, indent=2, default=str)}")
    
    if response.status_code == 200:
        print(f"✅ Content approved")
        print(f"   Status: {data['status']}")
        print(f"   Approved at: {data.get('approved_at', 'N/A')}")
        return True
    else:
        print(f"❌ Failed to approve content")
        return False

def test_7_update_content_status():
    """Step 7: Mark content as posted"""
    print_section("TEST 7: Update Content to Posted")
    
    if not CONTENT_ID:
        print("❌ No content ID available")
        return False
    
    response = requests.patch(
        f"{BASE_URL}/api/content/{CONTENT_ID}",
        json={"status": "posted"}
    )
    
    print(f"Status: {response.status_code}")
    data = response.json()
    print(f"Response: {json.dumps(data, indent=2, default=str)}")
    
    if response.status_code == 200:
        print(f"✅ Content marked as posted")
        print(f"   Status: {data['status']}")
        print(f"   Posted at: {data.get('posted_at', 'N/A')}")
        return True
    else:
        print(f"❌ Failed to update content")
        return False

def test_8_get_pending_content():
    """Step 8: List pending content for workspace"""
    print_section("TEST 8: Get Pending Content")
    
    if not WORKSPACE_ID:
        print("❌ No workspace ID available")
        return False
    
    response = requests.get(f"{BASE_URL}/api/content/workspace/{WORKSPACE_ID}/pending")
    
    print(f"Status: {response.status_code}")
    data = response.json()
    print(f"Response: {json.dumps(data, indent=2, default=str)}")
    
    if response.status_code == 200:
        print(f"✅ Retrieved pending content")
        print(f"   Count: {len(data)}")
        return True
    else:
        print(f"❌ Failed to get pending content")
        return False

def run_all_tests():
    """Run all tests in sequence"""
    print("\n" + "="*60)
    print("  CONTENT LAYER TEST SUITE")
    print("  Testing content creation, approval, and lifecycle")
    print("="*60)
    
    tests = [
        test_1_create_workspace,
        test_2_create_workflow_with_caption_generator,
        test_3_run_workflow,
        test_4_list_content,
        test_5_get_content_details,
        test_6_approve_content,
        test_7_update_content_status,
        test_8_get_pending_content
    ]
    
    results = []
    for test in tests:
        try:
            result = test()
            results.append(result)
            if not result:
                print("\n⚠️  Test failed, but continuing...")
        except Exception as e:
            print(f"\n❌ Test exception: {str(e)}")
            results.append(False)
    
    # Summary
    print("\n" + "="*60)
    print("  TEST SUMMARY")
    print("="*60)
    passed = sum(results)
    total = len(results)
    print(f"Passed: {passed}/{total}")
    print(f"Failed: {total - passed}/{total}")
    
    if passed == total:
        print("\n✅ ALL TESTS PASSED!")
    else:
        print(f"\n⚠️  {total - passed} test(s) failed")

if __name__ == "__main__":
    run_all_tests()
