import { Injectable, Logger } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { Content, ContentType, ContentStatus } from '../../entities/content.entity';
import { S3Service } from '../../services/s3.service';

export interface BlogGenerationInput {
  workspaceId: string;
  topic: string;
  tone?: string;
  length?: number;
}

export interface BlogGenerationOutput {
  contentId: string;
  title: string;
  body: string;
  s3Url: string;
}

@Injectable()
export class GenerateBlogTool {
  private readonly logger = new Logger(GenerateBlogTool.name);

  constructor(
    @InjectRepository(Content)
    private readonly contentRepository: Repository<Content>,
    private readonly s3Service: S3Service,
  ) {}

  /**
   * Execute blog generation
   * This wraps the existing blog generation model
   */
  async execute(input: BlogGenerationInput): Promise<BlogGenerationOutput> {
    this.logger.log(`Generating blog for topic: ${input.topic}`);

    // TODO: Call your existing blog generation model here
    // For now, this is a placeholder that shows the structure
    const blogContent = await this.generateBlogContent(input);

    // Store in S3
    const s3Key = `blogs/${Date.now()}-${input.topic.replace(/\s+/g, '-')}.md`;
    const s3Url = await this.s3Service.uploadText(s3Key, blogContent.body);

    // Create Content record (MCP requirement: every output must be stored and traceable)
    const content = this.contentRepository.create({
      workspaceId: input.workspaceId,
      type: ContentType.BLOG,
      s3Url,
      textData: blogContent.body,
      status: ContentStatus.DRAFT,
    });

    await this.contentRepository.save(content);
    this.logger.log(`Blog content stored: ${content.id}`);

    return {
      contentId: content.id,
      title: blogContent.title,
      body: blogContent.body,
      s3Url,
    };
  }

  /**
   * Placeholder for actual blog generation logic
   * Replace this with your existing blog generation model
   */
  private async generateBlogContent(input: BlogGenerationInput): Promise<{ title: string; body: string }> {
    // TODO: Integrate your existing blog generation model here
    // This is where you'd call OpenAI, Claude, or your custom model
    
    const title = `${input.topic} - A Comprehensive Guide`;
    const body = `# ${title}\n\n${input.topic} is an important topic...\n\n[Content generated by AI model]`;

    return { title, body };
  }
}
